// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"myPage":{"path":"myPage","id":"myPage","file":"myPage.tsx"},"index":{"path":"/","id":"index","file":"index.js"},"user":{"path":"user","id":"user","file":"user.js"}},
    routeComponents: {
'myPage': React.lazy(() => import(/* webpackChunkName: "myPage" */'../../../src/pages/myPage.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "index" */'../../../src/pages/index.js')),
'user': React.lazy(() => import(/* webpackChunkName: "user" */'../../../src/pages/user.js')),
},
  };
}
